# Specifies labels to apply to issues in Project Mu repositories based on regular expressions.
#
# NOTE: This file applies to issues with issue_labeler_regex_version=1.
#
#       In order to allow issue templates to be updated as needed and have matching regular expressions
#       matched against the expected templates, a version number is used to associate a set of regular
#       expressions with a corresponding set of issue templates.
#
#       Backward compatible additions can be made without incrementing the issue_labeler_regex_version. A
#       new version only needs to be introduced for non-backward compatible changes between regular
#       expressions and issue templates.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# For more information, see:
# https://github.com/github/issue-labeler

# Maintenance: Keep labels organized in ascending alphabetical order - easier to scan, identify duplicates, etc.

# <This configuration file is currently empty but kept as a placeholder until it is needed>
