# Defines the configuration used for drafting new releases.
#
# IMPORTANT: Only use labels defined in the .github/Labels.yml file in this repo.
#
# NOTE: `semver:major`, `semver:minor`, and `semver:patch` can be used to force that
#       version to roll regardless of other labels.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# For more information, see:
# https://github.com/release-drafter/release-drafter

name-template: 'v$RESOLVED_VERSION '
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features & ✨ Enhancements'
    labels:
      - 'type:design-change'
      - 'type:enhancement'
      - 'type:feature-request'
  - title: '🐛 Bug Fixes'
    labels:
      - 'type:bug'
  - title: '🔐 Security Impacting'
    labels:
      - 'impact:security'
  - title: '📖 Documentation Updates'
    labels:
      - 'type:documentation'
  - title: '🛠️ Submodule Updates'
    labels:
      - 'type:submodules'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

# Maintenance: Keep labels organized in ascending alphabetical order - easier to scan, identify duplicates, etc.
version-resolver:
  major:
    labels:
      - 'impact:breaking-change'
      - 'semver:major'
  minor:
    labels:
      - 'semver:minor'
      - 'type:design-change'
      - 'type:enhancement'
      - 'type:feature-request'
  patch:
    labels:
      - 'impact:non-functional'
      - 'semver:patch'
      - 'type:bug'
      - 'type:documentation'
  default: patch

exclude-labels:
  - 'type:dependencies'
  - 'type:file-sync'
  - 'type:notes'
  - 'type:question'

exclude-contributors:
  - 'dependabot'
  - 'uefibot'

template: |
  ## Changes

  $CHANGES
