# Specifies the labels in PRs that impact semantic versioning calculations.
#
# IMPORTANT: Only use labels defined in the .github/Labels.yml file in this repo.
#
# NOTE: `semver:major`, `semver:minor`, and `semver:patch` can be used to force that
#       version to roll regardless of other labels.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# For more information, see:
# https://github.com/patrickjahns/version-drafter-action

# Maintenance: Keep content organized in ascending alphabetical order - easier to scan, identify duplicates, etc.

major-labels: [
  'impact:breaking-change',
  'semver:major'
  ]

minor-labels: [
  'semver:minor',
  'type:design-change',
  'type:enhancement',
  'type:feature-request'
  ]

patch-labels: [
  'impact:non-functional',
  'semver:patch',
  'type:bug',
  'type:documentation',
  'type:notes'
  ]
