# This workflow syncs GitHub labels to the integrating repository.
#
# The labels are declaratively defined in .github/Labels.yml.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# For more information, see:
# https://github.com/micnncim/action-label-syncer

name: Mu DevOps Git Label Sync Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - add_common_label_sync_workflow_init_in_devops_testing
    paths:
      - .github/Labels.yml

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync Labels
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: .github/Labels.yml
          repository: |
            makubacki/mu_basecore
          token: ${{ secrets.MAKUBACKI_MU_BASECORE }}
