# This workflow automatically applies labels to issues and pull requests
# based on regular expression matches against the content in the issue
# or pull request or file path pattern matches.
#
# The labels are declaratively defined in the following configuration files:
#   - File Path Patterns: .sync/workflows/config/file-path-labels.yml
#   - Regular Expressions for Issues: .sync/workflows/config/reg-ex-labels-issues-v1.yml
#   - Regular Expressions for Pull Requests: .sync/workflows/config/reg-ex-labels-pull-requests.yml
#
# These will be mapped to the following directories in repos that use this reusable workflow:
#   - File Path Patterns: .github/file-path-labels.yml
#   - Regular Expressions for Issues: .github/reg-ex-labels-issues-v1.yml
#   - Regular Expressions for Pull Requests: .github/reg-ex-labels-pull-requests.yml
#
# Ideally, curl (or wget) could be used to grab the files from mu_devops in this workflow file and once on
# the local runner, the file path could simply be passed to the actions. That is not currently possible as
# the actions are hardcoded to use the GitHub REST API to get the files in the local repo. If that is fixed
# (tracked in https://github.com/github/issue-labeler/issues/39) then that approach can be used.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# For more information, see:
# https://github.com/github/issue-labeler

name: Apply Labels Based on Message Content

on:
  workflow_call:

jobs:
  sync:
    name: Label Based on Messages
    runs-on: ubuntu-latest

    steps:
      - name: Apply Labels Based on PR File Paths
        uses: actions/labeler@v4
        with:
          configuration-path: .github/file-path-labels.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true

      # Note: This will automatically search for files with a version based on the version found in issue files.
      #       Example: If an issue contains `issue_labeler_regex_version=2`. This will look for the configuration
      #                file `reg-ex-labels-issues-v2.yml`.
      - name: Apply Labels Based on Issue Messages
        uses: github/issue-labeler@v2.5
        with:
          configuration-path: .github/reg-ex-labels-issues-v1.yml
          enable-versioned-regex: 1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          versioned-regex: 'issue_labeler_regex_version=(\d+)'

      - name: Apply Labels Based on PR Messages
        uses: github/issue-labeler@v2.5
        with:
          configuration-path: .github/reg-ex-labels-pull-requests.yml
          enable-versioned-regex: 0
          repo-token: ${{ secrets.GITHUB_TOKEN }}
